// 채팅 시스템 메시지 코드
export enum ChatTemplateCode {
  // 광고 제안 챕터
  ADVERTISER_AD_PROPOSAL_MESSAGE = 'ADVERTISER_AD_PROPOSAL_MESSAGE', // 광고 제안 메세지 [O]
  ADVERTISER_AD_PROPOSAL_UPDATE_MESSAGE = 'ADVERTISER_AD_PROPOSAL_UPDATE_MESSAGE', // 광고 제안 수정 메세지 [O]
  AUTHOR_AD_PROPOSAL_ACCEPT_MESSAGE = 'AUTHOR_AD_PROPOSAL_ACCEPT_MESSAGE', // 광고 제안 수락 메세지 [O]
  AUTHOR_AD_PROPOSAL_REJECT_MESSAGE = 'AUTHOR_AD_PROPOSAL_REJECT_MESSAGE', // 광고 제안 거절 메세지 [O]
  ADVERTISER_AD_PROPOSAL_ACCEPTED_MESSAGE = 'ADVERTISER_AD_PROPOSAL_ACCEPTED_MESSAGE', // 광고 제안 수락 메세지 [O]
  ADVERTISER_AD_PROPOSAL_REJECTED_MESSAGE = 'ADVERTISER_AD_PROPOSAL_REJECTED_MESSAGE', // 광고 제안 거절 메세지 [O]

  // 광고 계약 챕터
  ADVERTISER_AD_CONTRACT_REQUEST_COMPLETE_MESSAGE = 'ADVERTISER_AD_CONTRACT_REQUEST_COMPLETE_MESSAGE', // 광고 계약 완료 요청 메세지
  ADVERTISER_AD_CONTRACT_COMPLETE_MESSAGE = 'ADVERTISER_AD_CONTRACT_COMPLETE_MESSAGE', // 광고 계약 완료 메세지
  AUTHOR_AD_CONTRACT_REQUEST_COMPLETE_MESSAGE = 'AUTHOR_AD_CONTRACT_REQUEST_COMPLETE_MESSAGE', // 광고 계약 완료 요청 메세지
  AUTHOR_AD_CONTRACT_COMPLETE_MESSAGE = 'AUTHOR_AD_CONTRACT_COMPLETE_MESSAGE', // 광고 계약 완료 메세지

  // 광고 작업 챕터
  AUTHOR_AD_CONTI_WORK_START_NOTICE = 'AUTHOR_AD_CONTI_WORK_START_NOTICE', // 광고 콘티 작업 시작 알림 메세지
  AUTHOR_AD_CONTI_WORK_CONFIRM_REQUEST = 'AUTHOR_AD_CONTI_WORK_CONFIRM_REQUEST', // 광고 콘티 작업 컨펌 요청 메세지
  ADVERTISER_AD_CONTI_UPDATE_REQUEST = 'ADVERTISER_AD_CONTI_UPDATE_REQUEST', // 광고 콘티 작업 수정 요청 메세지
  ADVERTISER_AD_CONTI_CONFIRM_COMPLETE = 'ADVERTISER_AD_CONTI_CONFIRM_COMPLETE', // 광고 콘티 작업 컨펌 완료 메세지
  AUTHOR_AD_WORK_START_NOTICE = 'AUTHOR_AD_WORK_START_NOTICE', // 광고 작업 시작 알림 메세지
  AUTHOR_AD_WORK_CONFIRM_REQUEST = 'AUTHOR_AD_WORK_CONFIRM_REQUEST', // 광고 작업 컨펌 요청 메세지
  ADVERTISER_AD_WORK_UPDATE_REQUEST = 'ADVERTISER_AD_WORK_UPDATE_REQUEST', // 광고 작업 수정 요청 메세지
  ADVERTISER_AD_WORK_CONFIRM_COMPLETE = 'ADVERTISER_AD_WORK_CONFIRM_COMPLETE', // 광고 작업 컨펌 완료 메세지

  // 광고 집행 챕터
  AUTHOR_AD_EXECUTION_COMPLETE = 'AUTHOR_AD_EXECUTION_COMPLETE', // 광고 집행 완료 메세지
}
