export enum EventErrorCode {
  // 인증 관련
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // 사용자 관련
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_OFFLINE = 'USER_OFFLINE',

  // 채팅방 관련
  CHAT_ROOM_NOT_FOUND = 'CHAT_ROOM_NOT_FOUND',
  NOT_MEMBER = 'NOT_MEMBER',

  // 유효성 검사 관련
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // 시스템 관련
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
