// 작가 작업 상태
export enum AdProposalAuthorWorkStatus {
  WAITING = 'WAITING', // 작업 대기
  CONTE_CREATING = 'CONTE_CREATING', // 콘티 제작 중
  CONTE_CONFIRM_REQUESTED = 'CONTE_CONFIRM_REQUESTED', // 콘티 컨펌 요청
  CONTE_REVISING = 'CONTE_REVISING', // 콘티 수정 작업 중
  ARTWORK_CREATING = 'ARTWORK_CREATING', // 실작업물 제작 중
  ARTWORK_REVISION_REQUESTED = 'ARTWORK_REVISION_REQUESTED', // 실작업물 수정 요청됨
  ARTWORK_REVISING = 'ARTWORK_REVISING', // 실작업물 수정 작업 중
  SETTLEMENT_REQUESTED = 'SETTLEMENT_REQUESTED', // 정산 요청
  PUBLISHED = 'PUBLISHED', // 광고 게시
}
