name: Deploy to Development Environment

# 트리거 조건: develop 브랜치에 push될 때
on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

# 환경 설정
env:
  NODE_VERSION: '22'

jobs:
  # Docker 이미지 빌드 및 배포
  deploy:
    runs-on: ubuntu-latest
    environment: test # GitHub 환경 설정

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          run: |
            # SSH Connection Test
            touch /home/${{ secrets.EC2_USERNAME }}/test.txt
